import type { Metadata } from "next";

import { AppSidebar } from "@/components/navigation/app-sidebar";

import LayoutContainer from "@/components/navigation/layout-container";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppNavbar from "@/components/navigation/app-navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <LayoutContainer>
        <main className="h-screen flex flex-col">
          <AppNavbar />
          <div className="flex-1 py-4">{children}</div>
        </main>
      </LayoutContainer>
    </SidebarProvider>
  );
}
